# Generated by Django 4.2.4 on 2024-12-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pauta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                ("hora", models.TimeField(verbose_name="Hora")),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "situacao",
                    models.CharField(max_length=200, verbose_name="Sitauação"),
                ),
            ],
        ),
    ]
