# Generated by Django 4.2.4 on 2024-12-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pauta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pauta",
            name="intervalo_repeticao",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Intervalo de repetição em DIAS"
            ),
        ),
        migrations.AddField(
            model_name="pauta",
            name="numero_repeticoes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de repetições"
            ),
        ),
    ]
